name: build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'c_make.c'
  release:
    types:
      - published

jobs:
  macos:
    runs-on: macos-26
    permissions:
      contents: write
    steps:
      - name: Checkout 'cui'
        uses: actions/checkout@v4
        with:
          repository: jrng/cui
          path: cui
      - name: Checkout 'wl_sherlock'
        uses: actions/checkout@v4
        with:
          path: wl_sherlock
      - name: Build 'cui'
        run: |
          cd cui
          clang -o c_make c_make.c
          ./c_make setup build --verbose build_type=reldebug
          ./c_make build build --verbose --sequential
      - name: Install 'cui'
        run: |
          mkdir -p $HOME/opt/cui/include
          mkdir -p $HOME/opt/cui/lib64
          cp cui/include/cui.h $HOME/opt/cui/include/
          install -m 755 cui/build/libcui.a $HOME/opt/cui/lib64/libcui.a
      - name: Build 'wl_sherlock'
        run: |
          cd wl_sherlock
          clang -o c_make c_make.c
          ./c_make setup build --verbose build_type=reldebug
          ./c_make build build --verbose --sequential
      - name: Upload artifact to release
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wl_sherlock/build
          zip -r wl_sherlock-${{ github.event.release.tag_name }}_macos.zip wl_sherlock.app
          gh release upload ${{ github.event.release.tag_name }} wl_sherlock-${{ github.event.release.tag_name }}_macos.zip
  ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --yes libegl-dev libx11-dev libxrandr-dev libwayland-dev libxkbcommon-dev libgles-dev
      - name: Checkout 'cui'
        uses: actions/checkout@v4
        with:
          repository: jrng/cui
          path: cui
      - name: Checkout 'wl_sherlock'
        uses: actions/checkout@v4
        with:
          path: wl_sherlock
      - name: Build 'cui'
        run: |
          cd cui
          cc -o c_make c_make.c
          ./c_make setup build --verbose build_type=reldebug
          ./c_make build build --verbose --sequential
      - name: Install 'cui'
        run: |
          mkdir -p $HOME/opt/cui/include
          mkdir -p $HOME/opt/cui/lib64
          cp cui/include/cui.h $HOME/opt/cui/include/
          install -m 755 cui/build/libcui.a $HOME/opt/cui/lib64/libcui.a
      - name: Build 'wl_sherlock'
        run: |
          cd wl_sherlock
          cc -o c_make c_make.c
          ./c_make setup build --verbose build_type=reldebug
          ./c_make build build --verbose --sequential
      - name: Upload artifact to release
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wl_sherlock/build
          tar czvf wl_sherlock-${{ github.event.release.tag_name }}_linux-x86_64.tar.gz wl_sherlock
          gh release upload ${{ github.event.release.tag_name }} wl_sherlock-${{ github.event.release.tag_name }}_linux-x86_64.tar.gz
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 'cui'
        uses: actions/checkout@v4
        with:
          repository: jrng/cui
          path: cui
      - name: Checkout 'wl_sherlock'
        uses: actions/checkout@v4
        with:
          path: wl_sherlock
      - name: Build 'cui'
        shell: cmd
        run: |
          cd cui
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cl -nologo -Fec_make.exe -Foc_make.obj c_make.c
          c_make.exe setup build --verbose build_type=reldebug
          c_make.exe build build --verbose --sequential
      - name: Install 'cui'
        shell: cmd
        run: |
          mkdir c:\\cui
          copy cui\\include\\cui.h c:\\cui\\cui.h
          copy cui\\build\\cui.lib c:\\cui\\cui.lib
      - name: Build 'wl_sherlock'
        shell: cmd
        run: |
          cd wl_sherlock
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cl -nologo -Fec_make.exe -Foc_make.obj c_make.c
          c_make.exe setup build --verbose build_type=reldebug
          c_make.exe build build --verbose --sequential
      - name: Upload artifact to release
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: cmd
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd wl_sherlock//build
          copy wl_sherlock.exe wl_sherlock-${{ github.event.release.tag_name }}_windows-x86_64.exe
          gh release upload ${{ github.event.release.tag_name }} wl_sherlock-${{ github.event.release.tag_name }}_windows-x86_64.exe
